name: Python Check

on:
  schedule:
    # 01:00 UTC+8 -> 17:00
    # After nightly image released
    - cron: "0 17 * * *"
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python_check.yml'
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'pdm.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python_check.yml'
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'pdm.lock'
  merge_group:
  workflow_dispatch:

jobs:
  lint:
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pdm sync -d -G lint -v
    - name: Run Lint Checks
      run: |
        pdm run check

  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install libblas-dev liblapack-dev
        pdm sync -G :all --no-isolation

    - name: Install jq
      uses: dcarbone/install-jq-action@v2

    - name: Start Postgres
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        NIGHTLY_VERSION=$(curl 'https://registry.hub.docker.com/v2/repositories/tensorchord/pgvecto-rs/tags/?ordering=last_updated' | jq '.results[].name' | grep pg15 | head -n 1 | sed 's/"//g')
        docker run --name pgvecto-rs-demo -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d tensorchord/pgvecto-rs:${NIGHTLY_VERSION}
    
    - name: Run Tests
      run: |
        pdm run test